name: "Build macOS ARM64"

on:
  push:
    branches:
      - development

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: "0"
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "1"

jobs:
  build:
    name: "Build macOS ARM64"
    runs-on: macos-26
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: "Install Bash"
        run: brew install bash
        shell: bash

      - name: "Setup Cargo config"
        run: |
          mkdir -p ./../.cargo
          cp ./.cargo/workflow-config.toml ./../.cargo/config.toml
        shell: bash

      - name: "Setup Rust cache"
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          cache-bin: false
          cache-targets: false
          shared-key: macos-26

      - name: "Build bundle (macOS ARM64)"
        run: ./script/bundle-macos --arch aarch64
        shell: bash

      - name: "Upload bundle"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: zaku-macos-aarch64
          path: target/aarch64-apple-darwin/release/Zaku-*-macos-aarch64.dmg
          if-no-files-found: error
